// Metadata extraction for JPEG, PNG, WebP and GIF. Pixel data is never read.
import zlib from "node:zlib";
import { parseIptc, parsePhotoshop, parseTiff, xmpFlags } from "./exif.mjs";

/** @typedef {{ field: string, text: string, offset?: number, doc?: boolean }} MetaString */
/** @typedef {{ category: string, field: string, offset?: number }} MetaFlag */
/** @typedef {{ strings: MetaString[], flags: MetaFlag[], nested: { name: string, buf: Buffer }[] }} Meta */

const emptyMeta = () => ({ strings: [], flags: [], nested: [] });

function merge(into, part, prefix) {
  for (const s of part.strings ?? []) into.strings.push(prefix ? { ...s, field: `${prefix}:${s.field}` } : s);
  into.flags.push(...(part.flags ?? []));
  into.nested.push(...(part.nested ?? []));
}

function addXmp(meta, xml, offset, field = "xmp") {
  if (!xml.trim()) return;
  meta.strings.push({ field, text: xml, offset, doc: true });
  meta.flags.push(...xmpFlags(xml));
}

function printable(buf, min = 5) {
  return buf.toString("utf8").replace(/[^\p{L}\p{N}\p{P}\p{S} ]+/gu, "\n").split("\n").filter((s) => s.length >= min);
}

/** @returns {Meta} */
export function parseJpeg(buf) {
  const meta = emptyMeta();
  let i = 2;
  while (i + 4 <= buf.length) {
    if (buf[i] !== 0xff) {
      i++;
      continue;
    }
    const marker = buf[i + 1];
    if (marker === 0xff) {
      i++;
      continue;
    }
    if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7) || marker === 0x00) {
      i += 2;
      continue;
    }
    if (marker === 0xd9) {
      // end of image: anything after it is trailing data
      const rest = buf.subarray(i + 2);
      if (rest.length > 16) {
        meta.flags.push({ category: "meta/trailing-data", field: "jpeg", offset: i + 2 });
        for (const s of printable(rest)) meta.strings.push({ field: "jpeg:trailing", text: s, offset: i + 2 });
      }
      break;
    }
    const len = buf.readUInt16BE(i + 2);
    const start = i + 4;
    const end = Math.min(buf.length, i + 2 + len);
    const seg = buf.subarray(start, end);
    if (marker === 0xe1) {
      if (seg.subarray(0, 6).toString("latin1") === "Exif\0\0") {
        merge(meta, parseTiff(seg.subarray(6), "exif"));
      } else if (seg.subarray(0, 28).toString("latin1").startsWith("http://ns.adobe.com/xap/1.0/")) {
        addXmp(meta, seg.subarray(29).toString("utf8"), start);
      } else if (seg.subarray(0, 34).toString("latin1").startsWith("http://ns.adobe.com/xmp/extension/")) {
        addXmp(meta, seg.subarray(34).toString("utf8"), start, "xmp-ext");
      } else for (const s of printable(seg)) meta.strings.push({ field: "jpeg:app1", text: s, offset: start });
    } else if (marker === 0xed && seg.subarray(0, 13).toString("latin1") === "Photoshop 3.0") {
      merge(meta, parsePhotoshop(seg.subarray(14)));
    } else if (marker === 0xfe) {
      const text = seg.toString("utf8").replace(/\0+$/, "");
      if (text.trim()) {
        meta.strings.push({ field: "jpeg:comment", text, offset: start });
        if (!BENIGN_COMMENT.test(text.trim())) meta.flags.push({ category: "meta/comment", field: "jpeg:comment", offset: start });
      }
    } else if (marker >= 0xe0 && marker <= 0xef && marker !== 0xe0) {
      // APP2 (ICC, MPF), APP14 and others: look at readable strings only
      for (const s of printable(seg, 6)) meta.strings.push({ field: `jpeg:app${marker - 0xe0}`, text: s, offset: start });
    }
    if (marker === 0xda) {
      // start of scan: skip entropy-coded data up to the next real marker
      i = end;
      while (i + 1 < buf.length && !(buf[i] === 0xff && buf[i + 1] !== 0x00 && !(buf[i + 1] >= 0xd0 && buf[i + 1] <= 0xd7))) i++;
      continue;
    }
    i = i + 2 + len;
  }
  return meta;
}

/** Comments that encoders write on their own (they are still scanned, but they are not a finding by themselves). */
const BENIGN_COMMENT = /^(?:Blender:oiio:|CREATOR: gd-jpeg|Created with|Generated by|Optimized by|Lavc|Intel\(R\) JPEG|ImageMagick|Exif_JPEG|Compressed by|JPEG encoder)/i;

const PNG_PERSONAL = new Set(["author", "copyright", "creator", "source", "disclaimer", "warning", "email", "owner", "artist", "location", "gps"]);
const PNG_FREE_TEXT = new Set(["comment", "description", "title"]);
const PNG_BENIGN = new Set(["software", "date:create", "date:modify", "date:timestamp", "creation time", "interlace", "dpi"]);
const PNG_KNOWN_BINARY = new Set(["IHDR", "PLTE", "IDAT", "IEND", "gAMA", "cHRM", "sRGB", "pHYs", "sBIT", "bKGD", "tRNS", "hIST", "acTL", "fcTL", "fdAT", "tIME", "iCCP", "sPLT", "cICP", "mDCV", "cLLI"]);

function inflateCapped(buf) {
  try {
    return zlib.inflateSync(buf, { maxOutputLength: 16 * 1024 * 1024 });
  } catch {
    return null;
  }
}

/** @returns {Meta} */
export function parsePng(buf) {
  const meta = emptyMeta();
  let i = 8;
  const textField = (key, value, offset) => {
    const k = key.toLowerCase();
    if (k.startsWith("raw profile type")) {
      // ImageMagick stores profiles as text: a name line, a length line, then hex. Decode and parse EXIF and XMP.
      const hex = value.replace(/^\s*\S+\s+\d+\s*/, "").replace(/[^0-9a-f]/gi, "");
      const bytes = Buffer.from(hex.length % 2 ? hex.slice(0, -1) : hex, "hex");
      if (k.endsWith("exif")) merge(meta, parseTiff(bytes.subarray(0, 6).toString("latin1") === "Exif\0\0" ? bytes.subarray(6) : bytes, "exif"));
      else if (k.endsWith("xmp")) addXmp(meta, bytes.toString("utf8"), offset);
      else for (const s of printable(bytes)) meta.strings.push({ field: `png:${key}`, text: s, offset });
      return;
    }
    if (k === "xml:com.adobe.xmp") {
      addXmp(meta, value, offset);
      return;
    }
    if (value.trim()) meta.strings.push({ field: `png:${key}`, text: value, offset });
    if (value.trim() && (PNG_PERSONAL.has(k) || (PNG_FREE_TEXT.has(k) && !PNG_BENIGN.has(k) && !BENIGN_COMMENT.test(value.trim())))) {
      meta.flags.push({ category: PNG_PERSONAL.has(k) ? "meta/personal-field" : "meta/comment", field: `png:${key}`, offset });
    }
  };
  while (i + 12 <= buf.length) {
    const len = buf.readUInt32BE(i);
    const type = buf.subarray(i + 4, i + 8).toString("latin1");
    const dStart = i + 8;
    const dEnd = dStart + len;
    if (dEnd > buf.length) break;
    const data = buf.subarray(dStart, dEnd);
    if (type === "tEXt") {
      const z = data.indexOf(0);
      if (z > 0) textField(data.subarray(0, z).toString("latin1"), data.subarray(z + 1).toString("latin1"), dStart);
    } else if (type === "zTXt") {
      const z = data.indexOf(0);
      if (z > 0) {
        const out = inflateCapped(data.subarray(z + 2));
        if (out) textField(data.subarray(0, z).toString("latin1"), out.toString("latin1"), dStart);
      }
    } else if (type === "iTXt") {
      const z = data.indexOf(0);
      if (z > 0 && z + 3 < data.length) {
        const compressed = data[z + 1] === 1;
        const rest = data.subarray(z + 3);
        const z1 = rest.indexOf(0);
        const z2 = z1 >= 0 ? rest.indexOf(0, z1 + 1) : -1;
        if (z2 >= 0) {
          let body = rest.subarray(z2 + 1);
          if (compressed) body = inflateCapped(body) ?? Buffer.alloc(0);
          textField(data.subarray(0, z).toString("latin1"), body.toString("utf8"), dStart);
        }
      }
    } else if (type === "eXIf") {
      merge(meta, parseTiff(data, "exif"));
    } else if (!PNG_KNOWN_BINARY.has(type) && type[0] === type[0].toLowerCase()) {
      for (const s of printable(data)) meta.strings.push({ field: `png:${type}`, text: s, offset: dStart });
    } else if (type === "iCCP") {
      const z = data.indexOf(0);
      if (z > 0) meta.strings.push({ field: "png:iCCP", text: data.subarray(0, z).toString("latin1"), offset: dStart });
    }
    if (type === "IEND") break;
    i = dEnd + 4;
  }
  return meta;
}

/** @returns {Meta} */
export function parseWebp(buf) {
  const meta = emptyMeta();
  let i = 12;
  while (i + 8 <= buf.length) {
    const type = buf.subarray(i, i + 4).toString("latin1");
    const size = buf.readUInt32LE(i + 4);
    const dStart = i + 8;
    const dEnd = Math.min(buf.length, dStart + size);
    const data = buf.subarray(dStart, dEnd);
    if (type === "EXIF") {
      const tiff = data.subarray(0, 6).toString("latin1") === "Exif\0\0" ? data.subarray(6) : data;
      merge(meta, parseTiff(tiff, "exif"));
    } else if (type === "XMP ") addXmp(meta, data.toString("utf8"), dStart);
    else if (type === "ICCP") for (const s of printable(data, 6)) meta.strings.push({ field: "webp:ICCP", text: s, offset: dStart });
    else if (!["VP8 ", "VP8L", "VP8X", "ALPH", "ANIM", "ANMF"].includes(type)) {
      for (const s of printable(data)) meta.strings.push({ field: `webp:${type.trim()}`, text: s, offset: dStart });
    }
    i = dStart + size + (size % 2);
  }
  return meta;
}

/** @returns {Meta} */
export function parseGif(buf) {
  const meta = emptyMeta();
  // comment extensions: 21 FE <sub-blocks>; application extensions may carry XMP
  let i = 0;
  while ((i = buf.indexOf(0x21, i)) !== -1 && i + 2 < buf.length) {
    const kind = buf[i + 1];
    if (kind === 0xfe) {
      let p = i + 2;
      let text = "";
      while (p < buf.length && buf[p] !== 0) {
        text += buf.subarray(p + 1, p + 1 + buf[p]).toString("latin1");
        p += buf[p] + 1;
      }
      if (text.trim()) {
        meta.strings.push({ field: "gif:comment", text, offset: i });
        meta.flags.push({ category: "meta/comment", field: "gif:comment", offset: i });
      }
    }
    i++;
  }
  const xmp = buf.indexOf("<?xpacket");
  if (xmp >= 0) addXmp(meta, buf.subarray(xmp, Math.min(buf.length, xmp + 65536)).toString("utf8"), xmp);
  return meta;
}

export { printable, parseIptc };
